# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dupers < Formula
  desc "A batch viewer and extractor for large collections of zip archives."
  homepage "https://github.com/bengarrett/dupers"
  version "1.0.0"
  license "LGPL 3.0"
  depends_on :macos

  on_macos do
    url "https://github.com/bengarrett/homebrew-dupers/releases/download/v1.0.0/homebrew-dupers_darwin_all.tar.gz"
    sha256 "e8ec2bcdbaf1157600531b2760bcaa029994ef00c338f8a1613a6fd3b02abf8a"

    def install
      bin.install "dupers"
    end
  end

  test do
    system "#{bin}/dupers --version"
  end
end
